sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@latest
  - npm run build:dockerfile
  - docker build . -t wheel-wasm

script:
  - npm run lint